plugins {
    id 'org.jetbrains.kotlin.jvm' version '2.2.21'
    id 'maven-publish'
    id 'signing'
    id 'io.typst.spigradle.spigot-base' version '4.0.2'
}

repositories {
    mavenLocal()
    mavenCentral()
    spigotRepos {
        spigotmc()
        papermc()
    }
}

kotlin {
    jvmToolchain(17)
}

dependencies {
    api(project(':view-bukkit'))
    implementation('org.jetbrains.kotlin:kotlin-stdlib:2.2.21')
    compileOnly(spigots.paper.api)
}

registerPublish(this)